class_i = [
	"Aggravated Assault",
	"All Other Larceny", 
	"Arson",
	"Burglary/Breaking & Entering",
	"Motor Vehicle Theft",
	"Murder and Nonnegligent Manslaughter",
	"Negligent Manslaughter",
	"Rape",
	"Robbery",
	"Sexual Assault With An Object"
	]

class_ii = [
	"Animal Cruelty",
	"Assisting or Promoting Prostitution",
	"Betting/Wagering",
	"Bribery",
	"Counterfeiting/Forgery",
	"Credit Card/Automated Teller Machine Fraud",
	"Destruction/Damage/Vandalism of Property",
	"Drug Equipment Violations",
	"Drug/Narcotic Violations",
	"Embezzlement",
	"Extortion/Blackmail",
	"False Pretenses/Swindle/Confidence Game",
	"Fondling",
	"Gambling Equipment Violation",
	"Hacking/Computer Invasion",
	"Human Trafficking, Commercial Sex Acts",
	"Human Trafficking, Involuntary Servitude",
	"Identity Theft",
	"Impersonation",
	"Incest",
	"Intimidation",
	"Justifiable Homicide",
	"Kidnapping/Abduction",
	"Operating/Promoting/Assisting Gambling",
	"Pocket-picking",
	"Pornography/Obscene Material",
	"Prostitution",
	"Purchasing Prostitution",
	"Purse-snatching",
	"Shoplifting",
	"Simple Assault",
	"Sodomy",
	"Statutory Rape",
	"Stolen Property Offenses",
	"Theft From Building",
	"Theft From Coin-Operated Machine or Device",
	"Theft From Motor Vehicle",
	"Theft of Motor Vehicle Parts or Accessories",
	"Weapon Law Violations",
	"Welfare Fraud",
	"Wire Fraud"
	]